# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Language options
language: node_js
node_js:
  - '0.10'

# Coveralls.io options
env:
  global:
    secure: rg7yX3iB0rDavR+5AVDhEDUDFjHe/+U6AqyH64/8nlEDDCaJ2LsQvoOuJxi7gN0D8xTVAoke1Pd+aibeB/ipuVT12iAQIemZNnmsIzHdwTbCiPBgU68lWtrI3RyquW1rsBiuWdQIAbGXHh0ymbISj/1U//zPtCPUFicKPa4ZTZA=

# Npm publish options
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: CaA40+ZPE9FQK0YNTz4hcBrMK2+5ABvzmpkd3io/M0VGYLKVOW5m7qoRSNUrk2eIG2y5l7Og94v3Z9+S5ul79Bgifd1g11hZGlAkZKKWsAFX397L9XsFFQAHFaAT+DQ9Dpw7O4W3jn86Qfb9nuShfl4sjFP5456DnmbqvnksxjI=
