# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Language options
language: node_js
node_js:
  - '0.10'

# Coveralls.io options
env:
  global:
    secure: rg7yX3iB0rDavR+5AVDhEDUDFjHe/+U6AqyH64/8nlEDDCaJ2LsQvoOuJxi7gN0D8xTVAoke1Pd+aibeB/ipuVT12iAQIemZNnmsIzHdwTbCiPBgU68lWtrI3RyquW1rsBiuWdQIAbGXHh0ymbISj/1U//zPtCPUFicKPa4ZTZA=

# Npm publish options
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: QXP/Vf1A4XATZNFgs3RY1aATMbkVrfX72diW9pVLwRkiCj6g9J3dXkf0UZ2HVWeeUtUaKgSe6PAsnFe8RhFF7ATWhGNxFClb2nqnwl7O+SDh+oT9kZuJ/bHl+Z5CiANiVpgexUAyYD5L8gVhkuYtTHRZZhfrUmo2FAf9Vp1akt8=
